title = "deadbaed"
description = "broke my bed now it's dead"

# The URL the site will be built for
base_url = "https://blog.x4m3.rocks"

# css
compile_sass = true

# rss
generate_feed = true
feed_filename = "atom.xml"

# search
default_language = "en"
build_search_index = true
[search]
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "gruvbox-light"

[extra]
footer_links = [
    {url = "$BASE_URL/atom.xml", name = "RSS"},
    {url = "https://philippeloctaux.com", name = "Website"},
]
