name: leptos_ssg

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # clone leptos_ssg repo
      - uses: dtolnay/rust-toolchain@stable
      - run: git clone https://github.com/deadbaed/leptos_ssg

      # generate opengraph css
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p tailwindcss_4 --run 'tailwindcss --cwd ./leptos_ssg/opengraph' > opengraph_style.css

      # generate opengraph images + build blog and overwrite leptos_ssg depedency to cloned repo
      - run: nix-shell -p firefox geckodriver xvfb-run --run 'echo "geckodriver is ready"'
      - run: cargo build --release --features prod --config 'patch."https://github.com/deadbaed/leptos_ssg".leptos_ssg.path="./leptos_ssg"'
      - run: nix-shell -p firefox geckodriver xvfb-run --run 'xvfb-run --auto-servernum geckodriver' & sleep 10 && cargo run --release --features prod --config 'patch."https://github.com/deadbaed/leptos_ssg".leptos_ssg.path="./leptos_ssg"'

      # generate css with tailwind
      - run: nix-shell -p tailwindcss_4 --run 'tailwindcss --cwd ./leptos_ssg/src --minify' > target/blog/www/style.css

      # create archive of new deployment
      - run: echo $GITHUB_SHA > target/blog/deployment.txt
      - run: tar -acvf blog.tar.zst -C target blog/

      # prepare ssh connections
      - name: Prepare SSH connections
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOST }}" > ~/.ssh/known_hosts

      # deploy archive
      - name: Send deployment to server
        run: scp -C blog.tar.zst ${{ secrets.SSH_DESTINATION }}:/tmp
      - name: Deploy
        run: |
          ssh ${{ secrets.SSH_DESTINATION }} << 'EOF'
          # create temp folder
          tmp=$(mktemp -d) && \

          # extract new deployment
          pushd $tmp && \
          mv /tmp/blog.tar.zst . && \
          tar -xf blog.tar.zst && \
          echo "Extracted archive" && \
          mv blog /var/www/blog/new-deployment && \

          # backup current deployment, install new deployment
          pushd /var/www/blog && \
          current_deployment=blog-$(date -I)-$(cat ./current/deployment.txt).tar.zst && \
          tar -acf $current_deployment current/ --transform='s|current/|blog/|' && \
          echo "Current deployment is backed up as $current_deployment" && \
          exch new-deployment/ current/ && \
          echo "New deployment is live" && \

          # cleanup
          rm -rf new-deployment/ && \
          echo "Removed old deployment" && \
          rm -rf $tmp && \
          echo "Removed $tmp"
          EOF
