name: leptos_ssg

on:
  push:
    # branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      # clone leptos_ssg repo
      - run: git clone https://github.com/deadbaed/leptos_ssg

      # build blog and overwrite leptos_ssg depedency to cloned repo
      - run: cargo run --release --config 'patch."https://github.com/deadbaed/leptos_ssg".leptos_ssg.path="./leptos_ssg"'

      # generate css with tailwind
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p tailwindcss_4 --run 'tailwindcss --cwd ./leptos_ssg --minify' > target/blog/www/style.css

      # list files to deploy
      - run: tree target/blog
